version: '3.8'
services:

  app:
    container_name: python_container
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - db
    volumes:
      - ./app/src:/app-data
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks: 
      - backend-network
      - frontend-network

  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Welcome01}
      PGDATA: /data/postgres
    volumes:
       - db-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend-network

  pgadmin4:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    depends_on: 
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend-network
 
networks:
  backend-network:
  frontend-network:
 
volumes:
    app-data:
    db-data:
    pgadmin: